Location.create!([
  {name: "Monster Arena"},
  {name: "Gagazet - Mountain Cave"},
  {name: "Inside Sin, Omega Ruins"},
  {name: "Thunder Plains"},
  {name: "Gagazet - Mountain Cave, Inside Sin, Ruins of Zanarkand"},
  {name: "Sanubia Desert"},
  {name: "Calm Lands"},
  {name: "Lake Macalania"},
  {name: "Bevelle, Via Purifico"},
  {name: "Gagazet - Mountain Cave, Gagazet - Mountain Path"},
  {name: "Inside Sin"},
  {name: "Gagazet - Mountain Cave, Gagazet - Mountain Path, Ruins of Zanarkand"},
  {name: "Djose Highroad and Temple"},
  {name: "Gagazet - Mountain Cave, Ruins of Zanarkand"},
  {name: "Gagazet - Mountain Path"},
  {name: "Djose Highroad and Temple, Moonflow"},
  {name: "Omega Ruins"},
  {name: "Macalania Woods"},
  {name: "Bevelle, Home, Mi'ihen Highroad"},
  {name: "Sanubia Desert, Village of the Cactuars"},
  {name: "Home, Macalania Woods"},
  {name: "Mi'ihen Highroad"},
  {name: "Besaid"},
  {name: "Cavern of the Stolen Fayth"},
  {name: "Ruins of Zanarkand, Omega Ruins"},
  {name: "Kilika"},
  {name: "Calm Lands, Cavern of the Stolen Fayth"},
  {name: "Bevelle, Home, Lake Macalania"},
  {name: "Bevelle"},
  {name: "Via Purifico"},
  {name: "Moonflow"},
  {name: "Ruins of Zanarkand"},
  {name: ""},
  {name: "Mi'ihen Highroad, Mushroom Rock"},
  {name: "Djose Highroad and Temple, Moonflow, Mushroom Rock"},
  {name: "Mushroom Rock"},
  {name: "Besaid, Mushroom Rock"},
  {name: "Luca"},
  {name: "Ruins, Baaj Temple"},
  {name: "Home, Lake Macalania"},
  {name: "Cavern of the Stolen Fayth, Gagazet - Mountain Path"},
  {name: "Ruins"},
  {name: "Djose Highroad and Temple, Mushroom Rock"},
  {name: "Airship - Battle with Sin"},
  {name: "Besaid, Salvage Ship"},
  {name: "Bevelle, Ruins, Via Purifico"},
  {name: "S.S. Liki"},
  {name: "Destruction of Zanarkand"},
  {name: "Salvage Ship"},
  {name: "Luca, Mushroom Rock"}
]) if Location.count == 0
Monster.create!([
  {name: "Abadon", location_id: 1},
  {name: "Abyss Worm", location_id: 1},
  {name: "Achelous", location_id: 2},
  {name: "Adamantoise", location_id: 3},
  {name: "Aerouge", location_id: 4},
  {name: "Ahriman", location_id: 5},
  {name: "Alcyone", location_id: 6},
  {name: "Anacondaur", location_id: 7},
  {name: "Anima", location_id: 8},
  {name: "Aqua Flan", location_id: 9},
  {name: "Bandersnatch", location_id: 10},
  {name: "Barbatos", location_id: 11},
  {name: "Bashura", location_id: 12},
  {name: "Basilisk", location_id: 13},
  {name: "Bat Eye", location_id: 9},
  {name: "Behemoth", location_id: 14},
  {name: "Behemoth King", location_id: 11},
  {name: "Biran Ronso", location_id: 15},
  {name: "Bite Bug", location_id: 16},
  {name: "Black Element", location_id: 17},
  {name: "Blue Element", location_id: 18},
  {name: "Bomb", location_id: 19},
  {name: "Bomb King", location_id: 1},
  {name: "Braska's Final Aeon", location_id: 11},
  {name: "Buer", location_id: 4},
  {name: "Bunyip", location_id: 16},
  {name: "Cactuar", location_id: 20},
  {name: "Cactuar King", location_id: 1},
  {name: "Catastrophe", location_id: 1},
  {name: "Catoblepas", location_id: 1},
  {name: "Cave Iguion", location_id: 9},
  {name: "Chimera", location_id: 21},
  {name: "Chimera Brain", location_id: 7},
  {name: "Chimerageist", location_id: 1},
  {name: "Chocobo Eater", location_id: 22},
  {name: "Coeurl", location_id: 7},
  {name: "Coeurlregina", location_id: 1},
  {name: "Condor", location_id: 23},
  {name: "Crawler", location_id: 8},
  {name: "Dark Element", location_id: 24},
  {name: "Dark Flan", location_id: 14},
  {name: "Defender", location_id: 24},
  {name: "Defender X", location_id: 7},
  {name: "Defender Z", location_id: 25},
  {name: "Demonolith", location_id: 3},
  {name: "Dingo", location_id: 23},
  {name: "Dinonix", location_id: 26},
  {name: "Don Tonberry", location_id: 1},
  {name: "Dual Horn", location_id: 19},
  {name: "Earth Eater", location_id: 1},
  {name: "Epaaj", location_id: 27},
  {name: "Espada", location_id: 1},
  {name: "Evil Eye", location_id: 28},
  {name: "Evrae", location_id: 29},
  {name: "Evrae Altana", location_id: 30},
  {name: "Exoray", location_id: 11},
  {name: "Extractor", location_id: 31},
  {name: "Fafnir", location_id: 1},
  {name: "Fallen Monk", location_id: 32},
  {name: "Fallen Monk (Flamethrower)", location_id: 33},
  {name: "Fenrir", location_id: 1},
  {name: "Flame Flan", location_id: 7},
  {name: "Floating Death", location_id: 17},
  {name: "Floating Eye", location_id: 34},
  {name: "Funguar", location_id: 35},
  {name: "Gandarewa", location_id: 36},
  {name: "Garm", location_id: 16},
  {name: "Garuda", location_id: 37},
  {name: "Garuda (Luca)", location_id: 38},
  {name: "Gemini (A)", location_id: 3},
  {name: "Gemini (B)", location_id: 3},
  {name: "Geneaux's Tentacle", location_id: 33},
  {name: "Geosgaeno", location_id: 39},
  {name: "Ghost", location_id: 24},
  {name: "Gold Element", location_id: 4},
  {name: "Grat", location_id: 15},
  {name: "Great Malboro", location_id: 11},
  {name: "Greater Sphere", location_id: 1},
  {name: "Grenade", location_id: 15},
  {name: "Grendel", location_id: 14},
  {name: "Grothia", location_id: 30},
  {name: "Guado Guardian", location_id: 40},
  {name: "Guado Guardian (II)", location_id: 33},
  {name: "Guado Guardian (III)", location_id: 33},
  {name: "Halma", location_id: 17},
  {name: "Head", location_id: 33},
  {name: "Hornet", location_id: 1},
  {name: "Ice Flan", location_id: 8},
  {name: "Iguion", location_id: 18},
  {name: "Imp", location_id: 41},
  {name: "Ipiria", location_id: 36},
  {name: "Iron Giant", location_id: 4},
  {name: "Ironclad", location_id: 1},
  {name: "Jormungand", location_id: 1},
  {name: "Juggernault", location_id: 1},
  {name: "Jumbo Flan", location_id: 1},
  {name: "Killer Bee", location_id: 26},
  {name: "Kimahri", location_id: 23},
  {name: "Klikk", location_id: 42},
  {name: "Kottos", location_id: 1},
  {name: "Kusariqqu", location_id: 4},
  {name: "Lamashtu", location_id: 43},
  {name: "Land Worm", location_id: 11},
  {name: "Larva", location_id: 4},
  {name: "Left Fin", location_id: 44},
  {name: "Lord Ochu", location_id: 26},
  {name: "Machea", location_id: 17},
  {name: "Maelspike", location_id: 2},
  {name: "Mafdet", location_id: 33},
  {name: "Magic Urn", location_id: 24},
  {name: "Malboro", location_id: 7},
  {name: "Malboro Menace", location_id: 1},
  {name: "Mandragora", location_id: 14},
  {name: "Master Coeurl", location_id: 17},
  {name: "Master Tonberry", location_id: 17},
  {name: "Maze Larva", location_id: 30},
  {name: "Mech Defender", location_id: 10},
  {name: "Mech Guard", location_id: 6},
  {name: "Mech Gunner", location_id: 6},
  {name: "Mech Hunter", location_id: 24},
  {name: "Mech Leader", location_id: 10},
  {name: "Mech Scouter", location_id: 7},
  {name: "Melusine", location_id: 4},
  {name: "Mi'ihen Fang", location_id: 22},
  {name: "Mimic (A)", location_id: 17},
  {name: "Mimic (B)", location_id: 17},
  {name: "Mimic (C)", location_id: 17},
  {name: "Mimic (D)", location_id: 17},
  {name: "Mortibody", location_id: 30},
  {name: "Mortiorchis", location_id: 15},
  {name: "Murussu", location_id: 18},
  {name: "Mushussu", location_id: 6},
  {name: "Nebiros", location_id: 7},
  {name: "Nega Elemental", location_id: 1},
  {name: "Negator", location_id: 8},
  {name: "Nemesis", location_id: 1},
  {name: "Neslug", location_id: 1},
  {name: "Nidhogg", location_id: 10},
  {name: "Oblitzerator", location_id: 38},
  {name: "Ochu", location_id: 31},
  {name: "Octopus", location_id: 30},
  {name: "Ogre", location_id: 7},
  {name: "Omega Weapon", location_id: 17},
  {name: "One-Eye", location_id: 1},
  {name: "Ornitholestes", location_id: 1},
  {name: "Phlegyas", location_id: 30},
  {name: "Piranha", location_id: 45},
  {name: "Pterya", location_id: 30},
  {name: "Pteryx", location_id: 1},
  {name: "Puraboros", location_id: 17},
  {name: "Qactuar", location_id: 4},
  {name: "Ragora", location_id: 26},
  {name: "Raldo", location_id: 22},
  {name: "Raptor", location_id: 43},
  {name: "Red Element", location_id: 36},
  {name: "Remora", location_id: 30},
  {name: "Right Fin", location_id: 44},
  {name: "Sahagin", location_id: 46},
  {name: "Sahagin (II)", location_id: 33},
  {name: "Sahagin (III)", location_id: 33},
  {name: "Sahagin Chief", location_id: 38},
  {name: "Sanctuary Keeper", location_id: 2},
  {name: "Sand Wolf", location_id: 6},
  {name: "Sandragora", location_id: 6},
  {name: "Sandworm", location_id: 6},
  {name: "Seymour", location_id: 8},
  {name: "Seymour Flux", location_id: 15},
  {name: "Seymour Natus", location_id: 30},
  {name: "Seymour Omnis", location_id: 33},
  {name: "Shinryu", location_id: 1},
  {name: "Shred", location_id: 7},
  {name: "Simurgh", location_id: 13},
  {name: "Sin", location_id: 44},
  {name: "Sin (Core)", location_id: 44},
  {name: "Sin (Fin)", location_id: 47},
  {name: "Sinscale", location_id: 48},
  {name: "Sinscale (II)", location_id: 48},
  {name: "Sinscale (III)", location_id: 47},
  {name: "Sinspawn Ammes", location_id: 48},
  {name: "Sinspawn Echuilles", location_id: 47},
  {name: "Sinspawn Genais", location_id: 44},
  {name: "Sinspawn Geneaux", location_id: 26},
  {name: "Sinspawn Gui", location_id: 36},
  {name: "Sinspawn Gui (Arm)", location_id: 33},
  {name: "Skoll", location_id: 7},
  {name: "Sleep Sprout", location_id: 1},
  {name: "Snow Flan", location_id: 16},
  {name: "Snow Wolf", location_id: 8},
  {name: "Spathi", location_id: 33},
  {name: "Spectral Keeper", location_id: 32},
  {name: "Spherimorph", location_id: 18},
  {name: "Spirit", location_id: 17},
  {name: "Splasher", location_id: 2},
  {name: "Stratavis", location_id: 1},
  {name: "Swamp Mafdet", location_id: 33},
  {name: "Tanket", location_id: 1},
  {name: "Th'uban", location_id: 1},
  {name: "Thorn", location_id: 24},
  {name: "Thunder Flan", location_id: 36},
  {name: "Tonberry", location_id: 24},
  {name: "Tros", location_id: 49},
  {name: "Ultima Buster", location_id: 1},
  {name: "Ultima Weapon", location_id: 17},
  {name: "Valaha", location_id: 24},
  {name: "Varuna", location_id: 17},
  {name: "Vidatu", location_id: 1},
  {name: "Vorban", location_id: 1},
  {name: "Vouivre", location_id: 50},
  {name: "Warrior Monk", location_id: 9},
  {name: "Warrior Monk (Flamethrower)", location_id: 33},
  {name: "Wasp", location_id: 18},
  {name: "Water Flan", location_id: 23},
  {name: "Wendigo", location_id: 8},
  {name: "White Element", location_id: 22},
  {name: "Worker", location_id: 38},
  {name: "Wraith", location_id: 3},
  {name: "Xiphos", location_id: 18},
  {name: "YAT-97", location_id: 32},
  {name: "YAT-99", location_id: 9},
  {name: "Yellow Element", location_id: 26},
  {name: "Yenke Ronso", location_id: 15},
  {name: "YKT-11", location_id: 32},
  {name: "YKT-63", location_id: 9},
  {name: "Yojimbo", location_id: 24},
  {name: "Yowie", location_id: 24},
  {name: "Yu Yevon", location_id: 11},
  {name: "Yunalesca", location_id: 32},
  {name: "Yunalesca (2nd)", location_id: 32},
  {name: "Yunalesca (3rd)", location_id: 32},
  {name: "Zaurus", location_id: 17},
  {name: "Zu", location_id: 6}
]) if Monster.count == 0
Item.create!([
  {name: "Ability Distiller", effect: "Makes an enemy drop Ability Spheres", effect_type: "Battle"},
  {name: "Ability Sphere", effect: "Activates ability nodes on Sphere Grid", effect_type: "Sphere"},
  {name: "Accuracy Sphere", effect: "Turns empty node to Accuracy+4 node on Sphere Grid", effect_type: "Sphere"},
  {name: "Agility Sphere", effect: "Turns empty node to Agility+4 node on Sphere Grid", effect_type: "Sphere"},
  {name: "Al Bhed Potion", effect: "Cures Poison, Stone, Silence and restores 1000 HP of all allies", effect_type: "Battle"},
  {name: "Amulet", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Antarctic Wind", effect: "Deals Ice damage to an enemy", effect_type: "Battle"},
  {name: "Antidote", effect: "Cures Poison", effect_type: "Recovery"},
  {name: "Arctic Wind", effect: "Deals Ice damage to an enemy", effect_type: "Battle"},
  {name: "Attribute Sphere", effect: "Activates attribute node activated by ally on Sphere Grid", effect_type: "Sphere"},
  {name: "Blessed Gem", effect: "Deals damage to an enemy", effect_type: "Battle"},
  {name: "Blk Magic Sphere", effect: "Activates black magic node activated by ally on the Sphere Grid", effect_type: "Sphere"},
  {name: "Bomb Core", effect: "Deals Fire damage to an enemy", effect_type: "Battle"},
  {name: "Bomb Fragment", effect: "Deals Fire damage to an enemy", effect_type: "Battle"},
  {name: "Candle of Life", effect: "Casts Doom on an enemy", effect_type: "Battle"},
  {name: "Chocobo Feather", effect: "Casts Haste on one ally", effect_type: "Battle"},
  {name: "Chocobo Wing", effect: "Casts Haste on all allies", effect_type: "Battle"},
  {name: "Clear Sphere", effect: "Turns any node to empty node on Sphere Grid", effect_type: "Sphere"},
  {name: "Dark Matter", effect: "Does major damage to all enemies", effect_type: "Battle"},
  {name: "Defense Sphere", effect: "Turns empty node to Defense+4 node", effect_type: "Sphere"},
  {name: "Designer Wallet", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Door to Tomorrow", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Dragon Scale", effect: "Deals Water damage to an enemy", effect_type: "Battle"},
  {name: "Dream Powder", effect: "Deals damage and causes Sleep on all enemies", effect_type: "Battle"},
  {name: "Echo Screen", effect: "Cures Silence", effect_type: "Recovery"},
  {name: "Electro Marble", effect: "Deals Thunder damage to an enemy", effect_type: "Battle"},
  {name: "Elixir", effect: "Fully restores HP and MP of one character", effect_type: "Recovery"},
  {name: "Ether", effect: "Restores 100 MP of one ally", effect_type: "Recovery"},
  {name: "Evasion Sphere", effect: "Turns empty node to Evasion+4 node on Sphere Grid", effect_type: "Sphere"},
  {name: "Eye Drops", effect: "Cures Darkness", effect_type: "Recovery"},
  {name: "Farplane Shadow", effect: "Casts Death on an enemy", effect_type: "Battle"},
  {name: "Farplane Wind", effect: "Casts Death on all enemies", effect_type: "Battle"},
  {name: "Fire Gem", effect: "Deals Fire damage to all enemies", effect_type: "Battle"},
  {name: "Fish Scale", effect: "Deals Water damage to an enemy", effect_type: "Battle"},
  {name: "Fortune Sphere", effect: "Activates Luck node on Sphere Grid", effect_type: "Sphere"},
  {name: "Frag Grenade", effect: "Deals damage and uses Armor Break on all enemies", effect_type: "Battle"},
  {name: "Friend Sphere", effect: "Move to any ally's current location on Sphere Grid.", effect_type: "Sphere"},
  {name: "Gambler's Spirit", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Gold Hourglass", effect: "Damages all enemies and delays their next turn", effect_type: "Battle"},
  {name: "Grenade", effect: "Deals damage to all enemies", effect_type: "Battle"},
  {name: "Healing Spring", effect: "Casts Regen on one ally", effect_type: "Battle"},
  {name: "Healing Water", effect: "Fully restores HP of all allies", effect_type: "Battle"},
  {name: "Hi-Potion", effect: "Restores 1000 HP of one character", effect_type: "Recovery"},
  {name: "Holy Water", effect: "Cures Zombie and Curse", effect_type: "Recovery"},
  {name: "HP Sphere", effect: "Turns empty node to HP+4 node on Sphere Grid", effect_type: "Sphere"},
  {name: "Hypello Potion", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Ice Gem", effect: "Deals Ice damage to all enemies", effect_type: "Battle"},
  {name: "Light Curtain", effect: "Casts Protect on one ally", effect_type: "Battle"},
  {name: "Lightning Gem", effect: "Deals Thunder damage to all enemies", effect_type: "Battle"},
  {name: "Lightning Marble", effect: "Deals Thunder damage to an enemy", effect_type: "Battle"},
  {name: "Luck Sphere", effect: "Turns empty node to Luck+4 node on Sphere Grid", effect_type: "Sphere"},
  {name: "Lunar Curtain", effect: "Casts Shell on one ally", effect_type: "Battle"},
  {name: "Lv. 1 Key Sphere", effect: "Opens Lv. 1 locks on Sphere Grid", effect_type: "Sphere"},
  {name: "Lv. 2 Key Sphere", effect: "Opens Lv. 2 locks on Sphere Grid", effect_type: "Sphere"},
  {name: "Lv. 3 Key Sphere", effect: "Opens Lv. 3 locks on Sphere Grid", effect_type: "Sphere"},
  {name: "Lv. 4 Key Sphere", effect: "Opens Lv. 4 locks on Sphere Grid", effect_type: "Sphere"},
  {name: "Magic Def Sphere", effect: "Turns empty node into Magic Def+4 node", effect_type: "Sphere"},
  {name: "Magic Sphere", effect: "Turns empty node into Magic+4 node", effect_type: "Sphere"},
  {name: "Mana Distiller", effect: "Makes an enemy drop Mana Spheres", effect_type: "Battle"},
  {name: "Mana Sphere", effect: "Activates Magic, Magic Defense, or MP node on Sphere Grid", effect_type: "Sphere"},
  {name: "Mana Spring", effect: "Absorbs MP from an enemy", effect_type: "Battle"},
  {name: "Mana Tablet", effect: "Doubles max MP of one ally in battle", effect_type: "Battle"},
  {name: "Mana Tonic", effect: "Doubles max MP of all allies in battle", effect_type: "Battle"},
  {name: "Map", effect: "Displays world map", effect_type: "Misc"},
  {name: "Master Sphere", effect: "Activates any ability or attribute node on Sphere Grid", effect_type: "Sphere"},
  {name: "Mega Phoenix", effect: "Brings all dead allies back to life", effect_type: "Recovery"},
  {name: "Mega-Potion", effect: "Restores 2000 HP of all allies", effect_type: "Recovery"},
  {name: "Megalixir", effect: "Fully restores HP and MP of all allies", effect_type: "Recovery"},
  {name: "MP Sphere", effect: "Turns empty node to MP+30 node on Sphere Grid", effect_type: "Sphere"},
  {name: "Musk", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Pendulum", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Petrify Grenade", effect: "Turns all enemies to Stone", effect_type: "Battle"},
  {name: "Phoenix Down", effect: "Brings one ally back to life", effect_type: "Recovery"},
  {name: "Poison Fang", effect: "Deals damage and causes Poison on an enemy", effect_type: "Battle"},
  {name: "Potion", effect: "Restores 200 HP of one character", effect_type: "Recovery"},
  {name: "Power Distiller", effect: "Makes an enemy drop Power Spheres", effect_type: "Battle"},
  {name: "Power Sphere", effect: "Activates Strength, Defense, or HP node on Sphere Grid", effect_type: "Sphere"},
  {name: "Purifying Salt", effect: "Damages and casts Dispel on an enemy", effect_type: "Battle"},
  {name: "Remedy", effect: "Cures Berserk, Confusion, Darkness, Poison, Silence, Sleep, Slow, and Stone", effect_type: "Recovery"},
  {name: "Rename Card", effect: "Renames an aeon", effect_type: "Misc"},
  {name: "Return Sphere", effect: "Return to any previously activated node on Sphere Grid", effect_type: "Sphere"},
  {name: "Shadow Gem", effect: "Casts Demi on all enemies", effect_type: "Battle"},
  {name: "Shining Gem", effect: "Deals damage to an enemy", effect_type: "Battle"},
  {name: "Shining Thorn", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Silence Grenade", effect: "Deals damage and causes Silence on all enemies", effect_type: "Battle"},
  {name: "Silver Hourglass", effect: "Delays next turn of all enemies", effect_type: "Battle"},
  {name: "Skill Sphere", effect: "Activates skill node activated by ally on Sphere Grid", effect_type: "Sphere"},
  {name: "Sleeping Powder", effect: "Deals damage and causes Sleep on all enemies", effect_type: "Battle"},
  {name: "Smoke Bomb", effect: "Deals damage and causes Darkness on all enemies", effect_type: "Battle"},
  {name: "Soft", effect: "Cures Stone", effect_type: "Recovery"},
  {name: "Soul Spring", effect: "Absorbs HP and MP from an enemy", effect_type: "Battle"},
  {name: "Special Sphere", effect: "Activates special node activated by ally on Sphere Grid", effect_type: "Sphere"},
  {name: "Speed Distiller", effect: "Makes an enemy drop Speed Spheres", effect_type: "Battle"},
  {name: "Speed Sphere", effect: "Activates Accuracy, Agility, or Evasion node on Sphere Grid", effect_type: "Sphere"},
  {name: "Stamina Spring", effect: "Absorbs HP from an enemy", effect_type: "Battle"},
  {name: "Stamina Tablet", effect: "Doubles max HP of one ally in battle", effect_type: "Battle"},
  {name: "Stamina Tonic", effect: "Doubles max HP of all allies in battle", effect_type: "Battle"},
  {name: "Star Curtain", effect: "Casts Reflect on one ally", effect_type: "Battle"},
  {name: "Strength Sphere", effect: "Turns empty node to Strength+4 node on Sphere Grid", effect_type: "Sphere"},
  {name: "Supreme Gem", effect: "Deals damage to all enemies", effect_type: "Battle"},
  {name: "Teleport Sphere", effect: "Move to any node activated by ally on Sphere Grid", effect_type: "Sphere"},
  {name: "Tetra Elemental", effect: "Fully restores HP and casts NulBlaze, NulShock, NulTide and NulFrost on all allies", effect_type: "Battle"},
  {name: "Three Stars", effect: "Reduces MP cost of all abilities to 0 for all allies", effect_type: "Battle"},
  {name: "Turbo Ether", effect: "Restores 500 MP of one ally", effect_type: "Recovery"},
  {name: "Twin Stars", effect: "Reduces MP cost of all abilities to 0 for an ally", effect_type: "Battle"},
  {name: "Underdog's Secret", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Warp Sphere", effect: "Move to any node on the Sphere Grid", effect_type: "Sphere"},
  {name: "Water Gem", effect: "Deals Water damage to all enemies", effect_type: "Battle"},
  {name: "Wht Magic Sphere", effect: "Activates white magic node activated by ally on Sphere Grid", effect_type: "Sphere"},
  {name: "Wings to Discovery", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "Winning Formula", effect: "There seems to be some use for this...", effect_type: "Useless"},
  {name: "X-Potion", effect: "Fully restores HP of one ally", effect_type: "Recovery"}
]) if Item.count == 0
Ability.create!([
  {name: "Alchemy", ability_type: "Weapon", item_id: 42, item_amount: 4, effect: "Double effect of recovery items used by the character"},
  {name: "Auto-Haste", ability_type: "Armor", item_id: 17, item_amount: 80, effect: "Automatically casts Haste at beginning of battle"},
  {name: "Auto-Med", ability_type: "Armor", item_id: 79, item_amount: 20, effect: "Automatically use status recovery items when afflicted"},
  {name: "Auto-Phoenix", ability_type: "Armor", item_id: 66, item_amount: 20, effect: "Automatically use a Phoenix Down when killed"},
  {name: "Auto-Potion", ability_type: "Armor", item_id: 96, item_amount: 4, effect: "Automatically use HP recovery items when hit"},
  {name: "Auto-Protect", ability_type: "Armor", item_id: 48, item_amount: 70, effect: "Automatically casts Protect at beginning of battle"},
  {name: "Auto-Reflect", ability_type: "Armor", item_id: 98, item_amount: 40, effect: "Automatically casts Reflect at beginning of battle"},
  {name: "Auto-Regen", ability_type: "Armor", item_id: 41, item_amount: 80, effect: "Automatically casts Regen at beginning of battle"},
  {name: "Auto-Shell", ability_type: "Armor", item_id: 52, item_amount: 80, effect: "Automatically casts Shell at beginning of battle"},
  {name: "Berserk Ward", ability_type: "Armor", item_id: 46, item_amount: 8, effect: "Sometimes protects against Berserk"},
  {name: "Berserkproof", ability_type: "Armor", item_id: 46, item_amount: 32, effect: "Protects against Berserk"},
  {name: "Break Damage Limit", ability_type: "Weapon", item_id: 19, item_amount: 60, effect: "Allows attacks to do more than 9999 damage"},
  {name: "Break HP Limit", ability_type: "Armor", item_id: 110, item_amount: 30, effect: "HP can exceed 9999"},
  {name: "Break MP Limit", ability_type: "Armor", item_id: 103, item_amount: 30, effect: "MP can exceed 999"},
  {name: "Confuse Ward", ability_type: "Armor", item_id: 70, item_amount: 16, effect: "Sometimes protects against Confusion"},
  {name: "Confuseproof", ability_type: "Armor", item_id: 70, item_amount: 48, effect: "Protects against Confusion"},
  {name: "Counterattack", ability_type: "Weapon", item_id: 37, item_amount: 1, effect: "Automatic attack when characters is hit by a physical attack"},
  {name: "Curseproof", ability_type: "Armor", item_id: 102, item_amount: 12, effect: "Protects against Curse"},
  {name: "Dark Ward", ability_type: "Armor", item_id: 30, item_amount: 40, effect: "Sometimes protects against Darkness"},
  {name: "Darkproof", ability_type: "Armor", item_id: 89, item_amount: 10, effect: "Protects against Darkness"},
  {name: "Darkstrike", ability_type: "Weapon", item_id: 89, item_amount: 20, effect: "Physical attacks cause Darkness"},
  {name: "Darktouch", ability_type: "Weapon", item_id: 30, item_amount: 60, effect: "Physical attacks sometimes cause Darkness"},
  {name: "Death Ward", ability_type: "Armor", item_id: 31, item_amount: 15, effect: "Sometimes protects against instant Death"},
  {name: "Deathproof", ability_type: "Armor", item_id: 32, item_amount: 60, effect: "Protects against instant Death"},
  {name: "Deathstrike", ability_type: "Weapon", item_id: 32, item_amount: 60, effect: "Physical attacks cause Death"},
  {name: "Deathtouch", ability_type: "Weapon", item_id: 31, item_amount: 30, effect: "Physical attacks sometimes cause Death"},
  {name: "Defense +10%", ability_type: "Armor", item_id: 92, item_amount: 1, effect: "Increase Defense by 10%"},
  {name: "Defense +20%", ability_type: "Armor", item_id: 11, item_amount: 4, effect: "Increase Defense by 20%"},
  {name: "Defense +3%", ability_type: "Armor", item_id: 77, item_amount: 3, effect: "Increase Defense by 3%"},
  {name: "Defense +5%", ability_type: "Armor", item_id: 95, item_amount: 2, effect: "Increase Defense by 5%"},
  {name: "Double AP", ability_type: "Weapon", item_id: 68, item_amount: 20, effect: "AP is doubled after battle (only if character is in active party at end of battle)"},
  {name: "Double Overdrive", ability_type: "Weapon", item_id: 106, item_amount: 30, effect: "Overdrive Gauge charges twice as fast"},
  {name: "Evade & Counter", ability_type: "Weapon", item_id: 101, item_amount: 1, effect: "Automatic attack when character dodges a physical attack"},
  {name: "Fire Eater", ability_type: "Armor", item_id: 33, item_amount: 20, effect: "Fire attacks restore HP instead of doing damage"},
  {name: "Fire Ward", ability_type: "Armor", item_id: 14, item_amount: 4, effect: "Take half damage from Fire attacks"},
  {name: "Fireproof", ability_type: "Armor", item_id: 13, item_amount: 8, effect: "Take no damage from Fire attacks"},
  {name: "Firestrike", ability_type: "Weapon", item_id: 14, item_amount: 4, effect: "Physical attacks are Fire elemental"},
  {name: "First Strike", ability_type: "Weapon", item_id: 81, item_amount: 1, effect: "Your party gets the first turn during battle"},
  {name: "Gillionaire", ability_type: "Weapon", item_id: 21, item_amount: 30, effect: "Doubles amount of gil gained after battle"},
  {name: "Half MP Cost", ability_type: "Weapon", item_id: 105, item_amount: 20, effect: "Reduce Ability MP costs by half"},
  {name: "HP +10%", ability_type: "Armor", item_id: 91, item_amount: 3, effect: "Increase max HP by 10%"},
  {name: "HP +20%", ability_type: "Armor", item_id: 27, item_amount: 5, effect: "Increase max HP by 20%"},
  {name: "HP +30%", ability_type: "Armor", item_id: 97, item_amount: 1, effect: "Increase max HP by 30%"},
  {name: "HP +5%", ability_type: "Armor", item_id: 112, item_amount: 1, effect: "Increase max HP by 5%"},
  {name: "HP Stroll", ability_type: "Armor", item_id: 96, item_amount: 2, effect: "Recover HP while walking"},
  {name: "Ice Eater", ability_type: "Armor", item_id: 47, item_amount: 20, effect: "Ice attacks restore HP instead of doing damage"},
  {name: "Ice Ward", ability_type: "Armor", item_id: 7, item_amount: 4, effect: "Take half damage from Ice attacks"},
  {name: "Iceproof", ability_type: "Armor", item_id: 9, item_amount: 8, effect: "Take no damage from Ice attacks"},
  {name: "Icestrike", ability_type: "Weapon", item_id: 7, item_amount: 4, effect: "Physical attacks are Ice elemental"},
  {name: "Initiative", ability_type: "Weapon", item_id: 16, item_amount: 6, effect: "Increase change of getting a Preemptive strike"},
  {name: "Lightning Eater", ability_type: "Armor", item_id: 49, item_amount: 20, effect: "Thunder attacks restore HP instead of doing damage"},
  {name: "Lightning Ward", ability_type: "Armor", item_id: 26, item_amount: 4, effect: "Take half damage from Thunder attacks"},
  {name: "Lightningproof", ability_type: "Armor", item_id: 50, item_amount: 8, effect: "Take no damage from Thunder attacks"},
  {name: "Lightningstrike", ability_type: "Weapon", item_id: 26, item_amount: 4, effect: "Physical attacks are Thunder elemental"},
  {name: "Magic +10%", ability_type: "Weapon", item_id: 12, item_amount: 1, effect: "Increase Magic by 10%"},
  {name: "Magic +20%", ability_type: "Weapon", item_id: 100, item_amount: 4, effect: "Increase Magic by 20%"},
  {name: "Magic +3%", ability_type: "Weapon", item_id: 60, item_amount: 3, effect: "Increase Magic by 3%"},
  {name: "Magic +5%", ability_type: "Weapon", item_id: 61, item_amount: 2, effect: "Increase Magic by 5%"},
  {name: "Magic Booster", ability_type: "Weapon", item_id: 104, item_amount: 30, effect: "Increase Magic power for the price of increased MP cost"},
  {name: "Magic Counter", ability_type: "Weapon", item_id: 83, item_amount: 16, effect: "Automatic attack when character is hit by a magical attack"},
  {name: "Magic Def +10%", ability_type: "Armor", item_id: 109, item_amount: 1, effect: "Increase Magic Def by 10%"},
  {name: "Magic Def +20%", ability_type: "Armor", item_id: 11, item_amount: 4, effect: "Increase Magic Def by 20%"},
  {name: "Magic Def +3%", ability_type: "Armor", item_id: 60, item_amount: 3, effect: "Increase Magic Def by 3%"},
  {name: "Magic Def +5%", ability_type: "Armor", item_id: 61, item_amount: 2, effect: "Increase Magic Def by 5%"},
  {name: "Master Thief", ability_type: "Armor", item_id: 71, item_amount: 30, effect: "Always steal rare items"},
  {name: "MP +10%", ability_type: "Armor", item_id: 91, item_amount: 3, effect: "Increase max MP by 10%"},
  {name: "MP +20%", ability_type: "Armor", item_id: 27, item_amount: 5, effect: "Increase max MP by 20%"},
  {name: "MP +30%", ability_type: "Armor", item_id: 63, item_amount: 1, effect: "Increase max MP by 30%"},
  {name: "MP +5%", ability_type: "Armor", item_id: 28, item_amount: 1, effect: "Increase max MP by 5%"},
  {name: "MP Stroll", ability_type: "Armor", item_id: 62, item_amount: 2, effect: "Recover MP while walking"},
  {name: "No Encounters", ability_type: "Armor", item_id: 78, item_amount: 30, effect: "Party will not encounter random battles"},
  {name: "One MP Cost", ability_type: "Weapon", item_id: 103, item_amount: 20, effect: "Reduce Ability MP costs to one"},
  {name: "Overdrive -> AP", ability_type: "Weapon", item_id: 22, item_amount: 10, effect: "Earn more AP but Overdrive Gauge doesn't charge"},
  {name: "Pickpocket", ability_type: "Armor", item_id: 6, item_amount: 30, effect: "Increase chance to steal rare items"},
  {name: "Piercing", ability_type: "Weapon", item_id: 54, item_amount: 1, effect: "Physical attacks bypass enemy armor doing normal damage"},
  {name: "Poison Ward", ability_type: "Armor", item_id: 8, item_amount: 40, effect: "Sometimes protects against Poison"},
  {name: "Poisonproof", ability_type: "Armor", item_id: 74, item_amount: 12, effect: "Protects against Poison"},
  {name: "Poisonstrike", ability_type: "Weapon", item_id: 74, item_amount: 24, effect: "Physical attacks cause Poison"},
  {name: "Poisontouch", ability_type: "Weapon", item_id: 8, item_amount: 99, effect: "Physical attacks sometimes cause Poison"},
  {name: "Sensor", ability_type: "Weapon", item_id: 2, item_amount: 2, effect: "View the data of enemies during battle"},
  {name: "Silence Ward", ability_type: "Armor", item_id: 25, item_amount: 30, effect: "Sometimes protects against Silence"},
  {name: "Silenceproof", ability_type: "Armor", item_id: 85, item_amount: 10, effect: "Protects against Silence"},
  {name: "Silencestrike", ability_type: "Weapon", item_id: 85, item_amount: 20, effect: "Physical attacks cause Silence"},
  {name: "Silencetouch", ability_type: "Weapon", item_id: 25, item_amount: 60, effect: "Physical attacks sometimes cause Silence"},
  {name: "Sleep Ward", ability_type: "Armor", item_id: 88, item_amount: 6, effect: "Sometimes protects against Sleep"},
  {name: "Sleepproof", ability_type: "Armor", item_id: 24, item_amount: 8, effect: "Protects against Sleep"},
  {name: "Sleepstrike", ability_type: "Weapon", item_id: 24, item_amount: 16, effect: "Physical attacks cause Sleep"},
  {name: "Sleeptouch", ability_type: "Weapon", item_id: 88, item_amount: 10, effect: "Physical attacks sometimes cause Sleep"},
  {name: "Slow Ward", ability_type: "Armor", item_id: 86, item_amount: 10, effect: "Sometimes protects against Slow"},
  {name: "Slowproof", ability_type: "Armor", item_id: 39, item_amount: 20, effect: "Protects against Slow"},
  {name: "Slowstrike", ability_type: "Weapon", item_id: 39, item_amount: 30, effect: "Physical attacks cause Slow"},
  {name: "Slowtouch", ability_type: "Weapon", item_id: 86, item_amount: 16, effect: "Physical attacks sometimes cause Slow"},
  {name: "SOS Haste", ability_type: "Armor", item_id: 16, item_amount: 20, effect: "Casts Haste when HP is low"},
  {name: "SOS NulBlaze", ability_type: "Armor", item_id: 13, item_amount: 1, effect: "Casts NulBlaze when HP is low"},
  {name: "SOS NulFrost", ability_type: "Armor", item_id: 9, item_amount: 1, effect: "Casts NulFrost when HP is low"},
  {name: "SOS NulShock", ability_type: "Armor", item_id: 50, item_amount: 1, effect: "Casts NulShock when HP is low"},
  {name: "SOS NulTide", ability_type: "Armor", item_id: 23, item_amount: 1, effect: "Casts NulTide when HP is low"},
  {name: "SOS Overdrive", ability_type: "Weapon", item_id: 38, item_amount: 20, effect: "Overdrive Gauge charges twice as fast when HP is low"},
  {name: "SOS Protect", ability_type: "Armor", item_id: 48, item_amount: 8, effect: "Casts Protect when HP is low"},
  {name: "SOS Reflect", ability_type: "Armor", item_id: 98, item_amount: 8, effect: "Casts Reflect when HP is low"},
  {name: "SOS Regen", ability_type: "Armor", item_id: 41, item_amount: 12, effect: "Casts Regen when HP is low"},
  {name: "SOS Shell", ability_type: "Armor", item_id: 52, item_amount: 8, effect: "Casts Shell when HP is low"},
  {name: "Stone Ward", ability_type: "Armor", item_id: 90, item_amount: 30, effect: "Sometimes protects against Stone"},
  {name: "Stoneproof", ability_type: "Armor", item_id: 72, item_amount: 20, effect: "Protects against Stone"},
  {name: "Stonestrike", ability_type: "Weapon", item_id: 72, item_amount: 60, effect: "Physical attacks cause Stone"},
  {name: "Stonetouch", ability_type: "Weapon", item_id: 72, item_amount: 10, effect: "Physical attacks sometimes cause Stone"},
  {name: "Strength +10%", ability_type: "Weapon", item_id: 87, item_amount: 1, effect: "Increase Strength by 10%"},
  {name: "Strength +20%", ability_type: "Weapon", item_id: 100, item_amount: 4, effect: "Increase Strength by 20%"},
  {name: "Strength +3%", ability_type: "Weapon", item_id: 77, item_amount: 3, effect: "Increase Strength by 3%"},
  {name: "Strength +5%", ability_type: "Weapon", item_id: 95, item_amount: 2, effect: "Increase Strength by 5%"},
  {name: "Triple AP", ability_type: "Weapon", item_id: 110, item_amount: 50, effect: "AP is tripled after battle (only if character is in active party at end of battle)"},
  {name: "Triple Overdrive", ability_type: "Weapon", item_id: 111, item_amount: 30, effect: "Overdrive Gauge charges three times as fast"},
  {name: "Water Eater", ability_type: "Armor", item_id: 108, item_amount: 20, effect: "Water attacks restore HP instead of doing damage"},
  {name: "Water Ward", ability_type: "Armor", item_id: 34, item_amount: 4, effect: "Take half damage from Water attacks"},
  {name: "Waterproof", ability_type: "Armor", item_id: 23, item_amount: 8, effect: "Take no damage from Water attacks"},
  {name: "Waterstrike", ability_type: "Weapon", item_id: 34, item_amount: 4, effect: "Physical attacks are Water elemental"},
  {name: "Zombie Ward", ability_type: "Armor", item_id: 44, item_amount: 30, effect: "Sometimes protects against Zombie"},
  {name: "Zombieproof", ability_type: "Armor", item_id: 15, item_amount: 10, effect: "Protects against Zombie"},
  {name: "Zombiestrike", ability_type: "Weapon", item_id: 15, item_amount: 30, effect: "Physical attacks cause Zombie"},
  {name: "Zombietouch", ability_type: "Weapon", item_id: 44, item_amount: 70, effect: "Physical attacks sometimes cause Zombie"}
]) if Ability.count == 0
BribeDrop.create!([
  {monster_id: 3, item_id: 41, amount: 16, cost: 102000},
  {monster_id: 4, item_id: 92, amount: 6, cost: 1088000},
  {monster_id: 5, item_id: 50, amount: 4, cost: 4000},
  {monster_id: 6, item_id: 32, amount: 6, cost: 56000},
  {monster_id: 7, item_id: 66, amount: 2, cost: 8600},
  {monster_id: 8, item_id: 42, amount: 16, cost: 116000},
  {monster_id: 10, item_id: 108, amount: 15, cost: 40500},
  {monster_id: 11, item_id: 24, amount: 20, cost: 36000},
  {monster_id: 12, item_id: 101, amount: 20, cost: 1900000},
  {monster_id: 13, item_id: 96, amount: 80, cost: 340000},
  {monster_id: 14, item_id: 72, amount: 24, cost: 40500},
  {monster_id: 15, item_id: 85, amount: 12, cost: 7600},
  {monster_id: 16, item_id: 54, amount: 30, cost: 460000},
  {monster_id: 17, item_id: 103, amount: 14, cost: 1350000},
  {monster_id: 19, item_id: 74, amount: 2, cost: 4000},
  {monster_id: 20, item_id: 12, amount: 2, cost: 152000},
  {monster_id: 21, item_id: 108, amount: 9, cost: 30000},
  {monster_id: 22, item_id: 13, amount: 16, cost: 17000},
  {monster_id: 25, item_id: 70, amount: 2, cost: 4600},
  {monster_id: 26, item_id: 46, amount: 16, cost: 8000},
  {monster_id: 31, item_id: 72, amount: 6, cost: 11000},
  {monster_id: 32, item_id: 62, amount: 10, cost: 105000},
  {monster_id: 33, item_id: 56, amount: 2, cost: 196000},
  {monster_id: 36, item_id: 37, amount: 2, cost: 120000},
  {monster_id: 38, item_id: 89, amount: 3, cost: 1900},
  {monster_id: 40, item_id: 81, amount: 3, cost: 36000},
  {monster_id: 41, item_id: 109, amount: 2, cost: 256000},
  {monster_id: 42, item_id: 96, amount: 20, cost: 24000},
  {monster_id: 44, item_id: 21, amount: 5, cost: 846000},
  {monster_id: 45, item_id: 55, amount: 40, cost: 900000},
  {monster_id: 46, item_id: 88, amount: 4, cost: 2500},
  {monster_id: 47, item_id: 72, amount: 2, cost: 2800},
  {monster_id: 49, item_id: 43, amount: 60, cost: 37500},
  {monster_id: 51, item_id: 32, amount: 25, cost: 174000},
  {monster_id: 53, item_id: 70, amount: 3, cost: 6200},
  {monster_id: 56, item_id: 104, amount: 1, cost: 148000},
  {monster_id: 62, item_id: 33, amount: 10, cost: 30000},
  {monster_id: 63, item_id: 38, amount: 10, cost: 134000},
  {monster_id: 64, item_id: 70, amount: 1, cost: 2800},
  {monster_id: 65, item_id: 104, amount: 2, cost: 10800},
  {monster_id: 66, item_id: 50, amount: 3, cost: 2960},
  {monster_id: 67, item_id: 88, amount: 7, cost: 4800},
  {monster_id: 70, item_id: 97, amount: 10, cost: 720000},
  {monster_id: 71, item_id: 97, amount: 10, cost: 720000},
  {monster_id: 74, item_id: 66, amount: 38, cost: 199980},
  {monster_id: 75, item_id: 50, amount: 20, cost: 24000},
  {monster_id: 76, item_id: 79, amount: 40, cost: 80000},
  {monster_id: 77, item_id: 110, amount: 8, cost: 1280000},
  {monster_id: 79, item_id: 83, amount: 12, cost: 150000},
  {monster_id: 80, item_id: 67, amount: 60, cost: 190000},
  {monster_id: 83, item_id: 28, amount: 10, cost: 40000},
  {monster_id: 84, item_id: 112, amount: 30, cost: 52000},
  {monster_id: 85, item_id: 100, amount: 20, cost: 260000},
  {monster_id: 88, item_id: 47, amount: 9, cost: 27000},
  {monster_id: 89, item_id: 72, amount: 5, cost: 7400},
  {monster_id: 90, item_id: 53, amount: 4, cost: 17600},
  {monster_id: 91, item_id: 72, amount: 3, cost: 3600},
  {monster_id: 92, item_id: 97, amount: 1, cost: 72000},
  {monster_id: 97, item_id: 74, amount: 1, cost: 2200},
  {monster_id: 101, item_id: 86, amount: 20, cost: 8900},
  {monster_id: 102, item_id: 86, amount: 10, cost: 5500},
  {monster_id: 103, item_id: 19, amount: 2, cost: 1600000},
  {monster_id: 104, item_id: 84, amount: 10, cost: 29960},
  {monster_id: 106, item_id: 79, amount: 80, cost: 92980},
  {monster_id: 107, item_id: 17, amount: 60, cost: 360000},
  {monster_id: 108, item_id: 10, amount: 1, cost: 200000},
  {monster_id: 109, item_id: 46, amount: 28, cost: 14200},
  {monster_id: 111, item_id: 110, amount: 4, cost: 540000},
  {monster_id: 113, item_id: 81, amount: 24, cost: 620000},
  {monster_id: 114, item_id: 107, amount: 1, cost: 260000},
  {monster_id: 115, item_id: 71, amount: 3, cost: 960000},
  {monster_id: 116, item_id: 108, amount: 14, cost: 44440},
  {monster_id: 117, item_id: 5, amount: 99, cost: 174000},
  {monster_id: 118, item_id: 40, amount: 50, cost: 25600},
  {monster_id: 119, item_id: 5, amount: 40, cost: 56000},
  {monster_id: 120, item_id: 5, amount: 60, cost: 110000},
  {monster_id: 121, item_id: 22, amount: 2, cost: 74000},
  {monster_id: 122, item_id: 22, amount: 1, cost: 55000},
  {monster_id: 123, item_id: 72, amount: 4, cost: 5300},
  {monster_id: 124, item_id: 88, amount: 5, cost: 3200},
  {monster_id: 131, item_id: 46, amount: 24, cost: 11600},
  {monster_id: 132, item_id: 90, amount: 1, cost: 13600},
  {monster_id: 133, item_id: 74, amount: 6, cost: 14000},
  {monster_id: 138, item_id: 39, amount: 12, cost: 40000},
  {monster_id: 140, item_id: 79, amount: 70, cost: 144000},
  {monster_id: 141, item_id: 95, amount: 20, cost: 90000},
  {monster_id: 142, item_id: 95, amount: 50, cost: 188000},
  {monster_id: 146, item_id: 41, amount: 6, cost: 33600},
  {monster_id: 147, item_id: 108, amount: 1, cost: 1000},
  {monster_id: 150, item_id: 83, amount: 36, cost: 400000},
  {monster_id: 152, item_id: 79, amount: 8, cost: 15600},
  {monster_id: 153, item_id: 46, amount: 10, cost: 4800},
  {monster_id: 154, item_id: 72, amount: 3, cost: 4000},
  {monster_id: 155, item_id: 13, amount: 8, cost: 9000},
  {monster_id: 156, item_id: 108, amount: 20, cost: 60000},
  {monster_id: 159, item_id: 108, amount: 1, cost: 27600},
  {monster_id: 160, item_id: 108, amount: 1, cost: 7600},
  {monster_id: 163, item_id: 88, amount: 12, cost: 9000},
  {monster_id: 164, item_id: 79, amount: 99, cost: 255000},
  {monster_id: 165, item_id: 111, amount: 15, cost: 900000},
  {monster_id: 171, item_id: 46, amount: 50, cost: 39000},
  {monster_id: 172, item_id: 89, amount: 5, cost: 4000},
  {monster_id: 185, item_id: 24, amount: 12, cost: 20000},
  {monster_id: 187, item_id: 7, amount: 10, cost: 12000},
  {monster_id: 188, item_id: 88, amount: 11, cost: 8000},
  {monster_id: 192, item_id: 105, amount: 10, cost: 200000},
  {monster_id: 193, item_id: 23, amount: 12, cost: 4000},
  {monster_id: 195, item_id: 46, amount: 28, cost: 17000},
  {monster_id: 198, item_id: 104, amount: 16, cost: 81600},
  {monster_id: 199, item_id: 50, amount: 8, cost: 9000},
  {monster_id: 200, item_id: 6, amount: 2, cost: 270000},
  {monster_id: 203, item_id: 71, amount: 99, cost: 1400000},
  {monster_id: 204, item_id: 112, amount: 60, cost: 174000},
  {monster_id: 205, item_id: 68, amount: 20, cost: 1120000},
  {monster_id: 211, item_id: 74, amount: 3, cost: 7200},
  {monster_id: 212, item_id: 108, amount: 2, cost: 6300},
  {monster_id: 214, item_id: 7, amount: 7, cost: 7800},
  {monster_id: 216, item_id: 32, amount: 60, cost: 444440},
  {monster_id: 217, item_id: 68, amount: 1, cost: 54000},
  {monster_id: 218, item_id: 28, amount: 16, cost: 74000},
  {monster_id: 219, item_id: 28, amount: 10, cost: 54000},
  {monster_id: 220, item_id: 50, amount: 6, cost: 6000},
  {monster_id: 222, item_id: 27, amount: 12, cost: 124000},
  {monster_id: 223, item_id: 27, amount: 8, cost: 84000},
  {monster_id: 225, item_id: 72, amount: 12, cost: 18000},
  {monster_id: 230, item_id: 80, amount: 10, cost: 157000}
]) if BribeDrop.count == 0
KillDrop.create!([
  {monster_id: 1, item_id: 62, amount: 1, rare: false},
  {monster_id: 1, item_id: 19, amount: 1, rare: true},
  {monster_id: 2, item_id: 97, amount: 1, rare: false},
  {monster_id: 2, item_id: 19, amount: 1, rare: true},
  {monster_id: 3, item_id: 77, amount: 1, rare: false},
  {monster_id: 4, item_id: 77, amount: 2, rare: false},
  {monster_id: 5, item_id: 60, amount: 1, rare: false},
  {monster_id: 6, item_id: 2, amount: 1, rare: false},
  {monster_id: 6, item_id: 94, amount: 1, rare: true},
  {monster_id: 7, item_id: 94, amount: 1, rare: false},
  {monster_id: 8, item_id: 77, amount: 1, rare: false},
  {monster_id: 9, item_id: 2, amount: 1, rare: false},
  {monster_id: 10, item_id: 60, amount: 1, rare: false},
  {monster_id: 11, item_id: 77, amount: 1, rare: false},
  {monster_id: 12, item_id: 77, amount: 1, rare: false},
  {monster_id: 12, item_id: 81, amount: 1, rare: true},
  {monster_id: 13, item_id: 77, amount: 1, rare: false},
  {monster_id: 14, item_id: 2, amount: 1, rare: false},
  {monster_id: 15, item_id: 94, amount: 1, rare: false},
  {monster_id: 16, item_id: 77, amount: 1, rare: false},
  {monster_id: 17, item_id: 77, amount: 2, rare: false},
  {monster_id: 18, item_id: 81, amount: 1, rare: false},
  {monster_id: 18, item_id: 37, amount: 1, rare: true},
  {monster_id: 19, item_id: 94, amount: 1, rare: false},
  {monster_id: 20, item_id: 60, amount: 2, rare: false},
  {monster_id: 21, item_id: 60, amount: 1, rare: false},
  {monster_id: 22, item_id: 77, amount: 1, rare: false},
  {monster_id: 23, item_id: 22, amount: 1, rare: false},
  {monster_id: 23, item_id: 19, amount: 1, rare: true},
  {monster_id: 25, item_id: 94, amount: 1, rare: false},
  {monster_id: 26, item_id: 77, amount: 1, rare: false},
  {monster_id: 27, item_id: 94, amount: 2, rare: false},
  {monster_id: 27, item_id: 94, amount: 3, rare: true},
  {monster_id: 28, item_id: 11, amount: 3, rare: false},
  {monster_id: 28, item_id: 19, amount: 1, rare: true},
  {monster_id: 29, item_id: 21, amount: 1, rare: false},
  {monster_id: 29, item_id: 19, amount: 1, rare: true},
  {monster_id: 30, item_id: 103, amount: 1, rare: false},
  {monster_id: 30, item_id: 19, amount: 1, rare: true},
  {monster_id: 31, item_id: 94, amount: 1, rare: false},
  {monster_id: 31, item_id: 77, amount: 1, rare: true},
  {monster_id: 32, item_id: 2, amount: 1, rare: false},
  {monster_id: 32, item_id: 2, amount: 2, rare: true},
  {monster_id: 33, item_id: 2, amount: 1, rare: false},
  {monster_id: 33, item_id: 49, amount: 2, rare: true},
  {monster_id: 34, item_id: 81, amount: 1, rare: false},
  {monster_id: 34, item_id: 19, amount: 1, rare: true},
  {monster_id: 35, item_id: 53, amount: 2, rare: false},
  {monster_id: 36, item_id: 60, amount: 1, rare: false},
  {monster_id: 36, item_id: 60, amount: 2, rare: true},
  {monster_id: 37, item_id: 83, amount: 3, rare: false},
  {monster_id: 37, item_id: 19, amount: 1, rare: true},
  {monster_id: 38, item_id: 94, amount: 1, rare: false},
  {monster_id: 40, item_id: 60, amount: 1, rare: false},
  {monster_id: 41, item_id: 60, amount: 1, rare: false},
  {monster_id: 41, item_id: 60, amount: 2, rare: true},
  {monster_id: 42, item_id: 77, amount: 2, rare: false},
  {monster_id: 43, item_id: 54, amount: 1, rare: false},
  {monster_id: 44, item_id: 54, amount: 1, rare: false},
  {monster_id: 44, item_id: 55, amount: 1, rare: true},
  {monster_id: 45, item_id: 60, amount: 2, rare: false},
  {monster_id: 46, item_id: 77, amount: 1, rare: false},
  {monster_id: 47, item_id: 94, amount: 1, rare: false},
  {monster_id: 47, item_id: 77, amount: 1, rare: true},
  {monster_id: 48, item_id: 32, amount: 3, rare: false},
  {monster_id: 48, item_id: 19, amount: 1, rare: true},
  {monster_id: 49, item_id: 2, amount: 1, rare: false},
  {monster_id: 50, item_id: 35, amount: 1, rare: false},
  {monster_id: 50, item_id: 19, amount: 1, rare: true},
  {monster_id: 51, item_id: 2, amount: 1, rare: false},
  {monster_id: 52, item_id: 80, amount: 1, rare: false},
  {monster_id: 52, item_id: 19, amount: 1, rare: true},
  {monster_id: 53, item_id: 94, amount: 1, rare: false},
  {monster_id: 54, item_id: 12, amount: 1, rare: false},
  {monster_id: 55, item_id: 12, amount: 1, rare: false},
  {monster_id: 56, item_id: 60, amount: 1, rare: false},
  {monster_id: 57, item_id: 66, amount: 1, rare: false},
  {monster_id: 58, item_id: 48, amount: 20, rare: false},
  {monster_id: 58, item_id: 19, amount: 1, rare: true},
  {monster_id: 59, item_id: 2, amount: 1, rare: false},
  {monster_id: 60, item_id: 2, amount: 1, rare: false},
  {monster_id: 61, item_id: 4, amount: 1, rare: false},
  {monster_id: 61, item_id: 19, amount: 1, rare: true},
  {monster_id: 62, item_id: 60, amount: 1, rare: false},
  {monster_id: 63, item_id: 60, amount: 2, rare: false},
  {monster_id: 64, item_id: 94, amount: 1, rare: false},
  {monster_id: 65, item_id: 60, amount: 1, rare: false},
  {monster_id: 66, item_id: 60, amount: 1, rare: false},
  {monster_id: 67, item_id: 77, amount: 1, rare: false},
  {monster_id: 68, item_id: 77, amount: 1, rare: false},
  {monster_id: 69, item_id: 77, amount: 1, rare: false},
  {monster_id: 70, item_id: 77, amount: 1, rare: false},
  {monster_id: 70, item_id: 77, amount: 2, rare: true},
  {monster_id: 71, item_id: 77, amount: 1, rare: false},
  {monster_id: 71, item_id: 77, amount: 2, rare: true},
  {monster_id: 72, item_id: 2, amount: 1, rare: false},
  {monster_id: 74, item_id: 60, amount: 1, rare: false},
  {monster_id: 75, item_id: 60, amount: 1, rare: false},
  {monster_id: 76, item_id: 60, amount: 1, rare: false},
  {monster_id: 77, item_id: 60, amount: 2, rare: false},
  {monster_id: 78, item_id: 51, amount: 1, rare: false},
  {monster_id: 78, item_id: 19, amount: 1, rare: true},
  {monster_id: 79, item_id: 77, amount: 1, rare: false},
  {monster_id: 80, item_id: 2, amount: 1, rare: false},
  {monster_id: 80, item_id: 2, amount: 2, rare: true},
  {monster_id: 82, item_id: 2, amount: 1, rare: false},
  {monster_id: 83, item_id: 2, amount: 1, rare: false},
  {monster_id: 84, item_id: 2, amount: 1, rare: false},
  {monster_id: 85, item_id: 77, amount: 1, rare: false},
  {monster_id: 85, item_id: 77, amount: 2, rare: true},
  {monster_id: 87, item_id: 3, amount: 1, rare: false},
  {monster_id: 87, item_id: 19, amount: 1, rare: true},
  {monster_id: 88, item_id: 60, amount: 1, rare: false},
  {monster_id: 89, item_id: 94, amount: 1, rare: false},
  {monster_id: 89, item_id: 77, amount: 1, rare: true},
  {monster_id: 90, item_id: 60, amount: 1, rare: false},
  {monster_id: 91, item_id: 94, amount: 1, rare: false},
  {monster_id: 91, item_id: 77, amount: 1, rare: true},
  {monster_id: 92, item_id: 77, amount: 2, rare: false},
  {monster_id: 92, item_id: 77, amount: 3, rare: true},
  {monster_id: 93, item_id: 45, amount: 1, rare: false},
  {monster_id: 93, item_id: 19, amount: 1, rare: true},
  {monster_id: 94, item_id: 100, amount: 2, rare: false},
  {monster_id: 94, item_id: 19, amount: 1, rare: true},
  {monster_id: 95, item_id: 99, amount: 1, rare: false},
  {monster_id: 95, item_id: 19, amount: 1, rare: true},
  {monster_id: 96, item_id: 58, amount: 1, rare: false},
  {monster_id: 96, item_id: 19, amount: 1, rare: true},
  {monster_id: 97, item_id: 94, amount: 1, rare: false},
  {monster_id: 98, item_id: 2, amount: 2, rare: false},
  {monster_id: 99, item_id: 2, amount: 2, rare: false},
  {monster_id: 100, item_id: 41, amount: 20, rare: false},
  {monster_id: 100, item_id: 19, amount: 1, rare: true},
  {monster_id: 101, item_id: 77, amount: 1, rare: false},
  {monster_id: 102, item_id: 77, amount: 1, rare: false},
  {monster_id: 103, item_id: 77, amount: 1, rare: false},
  {monster_id: 103, item_id: 56, amount: 1, rare: true},
  {monster_id: 104, item_id: 2, amount: 1, rare: false},
  {monster_id: 105, item_id: 45, amount: 1, rare: false},
  {monster_id: 106, item_id: 69, amount: 1, rare: false},
  {monster_id: 107, item_id: 60, amount: 1, rare: false},
  {monster_id: 107, item_id: 55, amount: 1, rare: true},
  {monster_id: 108, item_id: 60, amount: 1, rare: false},
  {monster_id: 109, item_id: 77, amount: 1, rare: false},
  {monster_id: 111, item_id: 60, amount: 2, rare: false},
  {monster_id: 112, item_id: 63, amount: 2, rare: false},
  {monster_id: 112, item_id: 19, amount: 1, rare: true},
  {monster_id: 113, item_id: 60, amount: 1, rare: false},
  {monster_id: 114, item_id: 53, amount: 1, rare: false},
  {monster_id: 114, item_id: 37, amount: 1, rare: true},
  {monster_id: 115, item_id: 77, amount: 1, rare: false},
  {monster_id: 115, item_id: 101, amount: 1, rare: true},
  {monster_id: 116, item_id: 2, amount: 1, rare: false},
  {monster_id: 117, item_id: 73, amount: 1, rare: false},
  {monster_id: 117, item_id: 66, amount: 1, rare: true},
  {monster_id: 118, item_id: 43, amount: 1, rare: false},
  {monster_id: 119, item_id: 43, amount: 2, rare: false},
  {monster_id: 120, item_id: 73, amount: 1, rare: false},
  {monster_id: 120, item_id: 66, amount: 1, rare: true},
  {monster_id: 121, item_id: 43, amount: 1, rare: false},
  {monster_id: 121, item_id: 67, amount: 1, rare: true},
  {monster_id: 122, item_id: 43, amount: 1, rare: false},
  {monster_id: 122, item_id: 67, amount: 1, rare: true},
  {monster_id: 123, item_id: 94, amount: 1, rare: false},
  {monster_id: 123, item_id: 77, amount: 1, rare: true},
  {monster_id: 124, item_id: 77, amount: 1, rare: false},
  {monster_id: 131, item_id: 77, amount: 1, rare: false},
  {monster_id: 132, item_id: 77, amount: 1, rare: false},
  {monster_id: 133, item_id: 60, amount: 1, rare: false},
  {monster_id: 134, item_id: 105, amount: 2, rare: false},
  {monster_id: 134, item_id: 19, amount: 1, rare: true},
  {monster_id: 135, item_id: 75, amount: 1, rare: false},
  {monster_id: 135, item_id: 43, amount: 1, rare: true},
  {monster_id: 136, item_id: 107, amount: 1, rare: false},
  {monster_id: 136, item_id: 19, amount: 1, rare: true},
  {monster_id: 137, item_id: 71, amount: 1, rare: false},
  {monster_id: 137, item_id: 19, amount: 1, rare: true},
  {monster_id: 138, item_id: 77, amount: 1, rare: false},
  {monster_id: 140, item_id: 77, amount: 1, rare: false},
  {monster_id: 140, item_id: 60, amount: 2, rare: true},
  {monster_id: 141, item_id: 60, amount: 1, rare: false},
  {monster_id: 142, item_id: 77, amount: 1, rare: false},
  {monster_id: 143, item_id: 56, amount: 3, rare: false},
  {monster_id: 144, item_id: 57, amount: 1, rare: false},
  {monster_id: 144, item_id: 19, amount: 1, rare: true},
  {monster_id: 145, item_id: 38, amount: 2, rare: false},
  {monster_id: 145, item_id: 19, amount: 1, rare: true},
  {monster_id: 146, item_id: 77, amount: 1, rare: false},
  {monster_id: 147, item_id: 77, amount: 1, rare: false},
  {monster_id: 147, item_id: 2, amount: 1, rare: true},
  {monster_id: 149, item_id: 29, amount: 1, rare: false},
  {monster_id: 149, item_id: 19, amount: 1, rare: true},
  {monster_id: 150, item_id: 60, amount: 1, rare: false},
  {monster_id: 150, item_id: 53, amount: 1, rare: true},
  {monster_id: 151, item_id: 94, amount: 1, rare: false},
  {monster_id: 151, item_id: 94, amount: 2, rare: true},
  {monster_id: 152, item_id: 60, amount: 1, rare: false},
  {monster_id: 153, item_id: 77, amount: 1, rare: false},
  {monster_id: 154, item_id: 94, amount: 1, rare: false},
  {monster_id: 154, item_id: 77, amount: 1, rare: true},
  {monster_id: 155, item_id: 60, amount: 1, rare: false},
  {monster_id: 156, item_id: 60, amount: 1, rare: false},
  {monster_id: 157, item_id: 55, amount: 1, rare: false},
  {monster_id: 159, item_id: 77, amount: 1, rare: false},
  {monster_id: 160, item_id: 77, amount: 1, rare: false},
  {monster_id: 161, item_id: 77, amount: 1, rare: false},
  {monster_id: 162, item_id: 81, amount: 1, rare: false},
  {monster_id: 163, item_id: 77, amount: 1, rare: false},
  {monster_id: 163, item_id: 5, amount: 1, rare: true},
  {monster_id: 164, item_id: 60, amount: 1, rare: false},
  {monster_id: 165, item_id: 2, amount: 2, rare: false},
  {monster_id: 165, item_id: 53, amount: 1, rare: true},
  {monster_id: 166, item_id: 12, amount: 1, rare: false},
  {monster_id: 166, item_id: 92, amount: 1, rare: true},
  {monster_id: 167, item_id: 56, amount: 1, rare: false},
  {monster_id: 168, item_id: 54, amount: 2, rare: false},
  {monster_id: 169, item_id: 55, amount: 1, rare: false},
  {monster_id: 169, item_id: 55, amount: 2, rare: true},
  {monster_id: 170, item_id: 110, amount: 1, rare: false},
  {monster_id: 170, item_id: 19, amount: 1, rare: true},
  {monster_id: 171, item_id: 94, amount: 1, rare: false},
  {monster_id: 172, item_id: 94, amount: 1, rare: false},
  {monster_id: 173, item_id: 55, amount: 1, rare: false},
  {monster_id: 174, item_id: 69, amount: 1, rare: false},
  {monster_id: 175, item_id: 60, amount: 1, rare: false},
  {monster_id: 177, item_id: 60, amount: 1, rare: false},
  {monster_id: 178, item_id: 60, amount: 1, rare: false},
  {monster_id: 180, item_id: 2, amount: 2, rare: false},
  {monster_id: 181, item_id: 81, amount: 1, rare: false},
  {monster_id: 182, item_id: 77, amount: 2, rare: false},
  {monster_id: 182, item_id: 77, amount: 3, rare: true},
  {monster_id: 185, item_id: 77, amount: 1, rare: false},
  {monster_id: 186, item_id: 101, amount: 1, rare: false},
  {monster_id: 186, item_id: 19, amount: 1, rare: true},
  {monster_id: 187, item_id: 60, amount: 1, rare: false},
  {monster_id: 188, item_id: 77, amount: 1, rare: false},
  {monster_id: 190, item_id: 56, amount: 1, rare: false},
  {monster_id: 191, item_id: 54, amount: 1, rare: false},
  {monster_id: 192, item_id: 60, amount: 1, rare: false},
  {monster_id: 192, item_id: 37, amount: 1, rare: true},
  {monster_id: 193, item_id: 77, amount: 1, rare: false},
  {monster_id: 194, item_id: 6, amount: 2, rare: false},
  {monster_id: 194, item_id: 19, amount: 1, rare: true},
  {monster_id: 196, item_id: 20, amount: 1, rare: false},
  {monster_id: 196, item_id: 19, amount: 1, rare: true},
  {monster_id: 197, item_id: 106, amount: 1, rare: false},
  {monster_id: 197, item_id: 19, amount: 1, rare: true},
  {monster_id: 198, item_id: 60, amount: 1, rare: false},
  {monster_id: 199, item_id: 60, amount: 1, rare: false},
  {monster_id: 200, item_id: 77, amount: 1, rare: false},
  {monster_id: 200, item_id: 54, amount: 1, rare: true},
  {monster_id: 201, item_id: 77, amount: 2, rare: false},
  {monster_id: 202, item_id: 111, amount: 1, rare: false},
  {monster_id: 202, item_id: 19, amount: 1, rare: true},
  {monster_id: 203, item_id: 55, amount: 3, rare: false},
  {monster_id: 204, item_id: 2, amount: 1, rare: false},
  {monster_id: 205, item_id: 58, amount: 1, rare: false},
  {monster_id: 205, item_id: 54, amount: 1, rare: true},
  {monster_id: 206, item_id: 69, amount: 1, rare: false},
  {monster_id: 206, item_id: 19, amount: 1, rare: true},
  {monster_id: 207, item_id: 37, amount: 1, rare: false},
  {monster_id: 207, item_id: 19, amount: 1, rare: true},
  {monster_id: 209, item_id: 2, amount: 1, rare: false},
  {monster_id: 210, item_id: 2, amount: 1, rare: false},
  {monster_id: 211, item_id: 94, amount: 1, rare: false},
  {monster_id: 212, item_id: 60, amount: 1, rare: false},
  {monster_id: 213, item_id: 77, amount: 1, rare: false},
  {monster_id: 213, item_id: 77, amount: 2, rare: true},
  {monster_id: 214, item_id: 60, amount: 1, rare: false},
  {monster_id: 215, item_id: 43, amount: 1, rare: false},
  {monster_id: 215, item_id: 112, amount: 1, rare: true},
  {monster_id: 216, item_id: 58, amount: 1, rare: false},
  {monster_id: 216, item_id: 58, amount: 2, rare: true},
  {monster_id: 217, item_id: 2, amount: 1, rare: false},
  {monster_id: 217, item_id: 2, amount: 2, rare: true},
  {monster_id: 218, item_id: 66, amount: 1, rare: true},
  {monster_id: 219, item_id: 73, amount: 1, rare: false},
  {monster_id: 219, item_id: 66, amount: 1, rare: true},
  {monster_id: 220, item_id: 60, amount: 1, rare: false},
  {monster_id: 221, item_id: 81, amount: 1, rare: false},
  {monster_id: 221, item_id: 37, amount: 1, rare: true},
  {monster_id: 222, item_id: 43, amount: 2, rare: false},
  {monster_id: 222, item_id: 67, amount: 1, rare: true},
  {monster_id: 223, item_id: 43, amount: 1, rare: false},
  {monster_id: 223, item_id: 67, amount: 1, rare: true},
  {monster_id: 225, item_id: 94, amount: 1, rare: false},
  {monster_id: 225, item_id: 77, amount: 1, rare: true},
  {monster_id: 229, item_id: 55, amount: 1, rare: false},
  {monster_id: 230, item_id: 94, amount: 2, rare: false},
  {monster_id: 231, item_id: 77, amount: 1, rare: false},
  {monster_id: 231, item_id: 77, amount: 2, rare: true}
]) if KillDrop.count == 0
StealDrop.create!([
  {monster_id: 1, item_id: 78, amount: 3, rare: false},
  {monster_id: 1, item_id: 83, amount: 1, rare: true},
  {monster_id: 2, item_id: 82, amount: 4, rare: false},
  {monster_id: 2, item_id: 96, amount: 1, rare: true},
  {monster_id: 3, item_id: 108, amount: 2, rare: false},
  {monster_id: 3, item_id: 41, amount: 1, rare: true},
  {monster_id: 4, item_id: 42, amount: 1, rare: false},
  {monster_id: 4, item_id: 96, amount: 1, rare: true},
  {monster_id: 5, item_id: 26, amount: 1, rare: false},
  {monster_id: 5, item_id: 50, amount: 1, rare: true},
  {monster_id: 6, item_id: 70, amount: 2, rare: false},
  {monster_id: 6, item_id: 70, amount: 3, rare: true},
  {monster_id: 7, item_id: 89, amount: 1, rare: false},
  {monster_id: 7, item_id: 89, amount: 2, rare: true},
  {monster_id: 8, item_id: 72, amount: 1, rare: false},
  {monster_id: 8, item_id: 72, amount: 2, rare: true},
  {monster_id: 9, item_id: 85, amount: 3, rare: false},
  {monster_id: 9, item_id: 31, amount: 1, rare: true},
  {monster_id: 10, item_id: 34, amount: 2, rare: false},
  {monster_id: 10, item_id: 23, amount: 2, rare: true},
  {monster_id: 11, item_id: 24, amount: 2, rare: false},
  {monster_id: 12, item_id: 98, amount: 1, rare: false},
  {monster_id: 12, item_id: 11, amount: 1, rare: true},
  {monster_id: 13, item_id: 91, amount: 1, rare: false},
  {monster_id: 13, item_id: 91, amount: 2, rare: true},
  {monster_id: 14, item_id: 72, amount: 1, rare: false},
  {monster_id: 15, item_id: 43, amount: 1, rare: false},
  {monster_id: 15, item_id: 85, amount: 1, rare: true},
  {monster_id: 16, item_id: 28, amount: 1, rare: false},
  {monster_id: 16, item_id: 62, amount: 1, rare: true},
  {monster_id: 17, item_id: 41, amount: 1, rare: false},
  {monster_id: 17, item_id: 105, amount: 2, rare: true},
  {monster_id: 18, item_id: 55, amount: 1, rare: false},
  {monster_id: 18, item_id: 55, amount: 2, rare: true},
  {monster_id: 19, item_id: 8, amount: 1, rare: false},
  {monster_id: 19, item_id: 74, amount: 1, rare: true},
  {monster_id: 20, item_id: 43, amount: 1, rare: false},
  {monster_id: 20, item_id: 83, amount: 4, rare: true},
  {monster_id: 21, item_id: 34, amount: 2, rare: false},
  {monster_id: 21, item_id: 34, amount: 3, rare: true},
  {monster_id: 22, item_id: 14, amount: 2, rare: false},
  {monster_id: 22, item_id: 14, amount: 3, rare: true},
  {monster_id: 23, item_id: 33, amount: 4, rare: false},
  {monster_id: 23, item_id: 83, amount: 1, rare: true},
  {monster_id: 24, item_id: 104, amount: 1, rare: false},
  {monster_id: 25, item_id: 43, amount: 1, rare: false},
  {monster_id: 25, item_id: 70, amount: 1, rare: true},
  {monster_id: 26, item_id: 43, amount: 1, rare: false},
  {monster_id: 26, item_id: 46, amount: 1, rare: true},
  {monster_id: 27, item_id: 16, amount: 1, rare: false},
  {monster_id: 27, item_id: 17, amount: 1, rare: true},
  {monster_id: 28, item_id: 17, amount: 2, rare: false},
  {monster_id: 28, item_id: 21, amount: 1, rare: true},
  {monster_id: 29, item_id: 38, amount: 1, rare: false},
  {monster_id: 29, item_id: 54, amount: 1, rare: true},
  {monster_id: 30, item_id: 41, amount: 3, rare: false},
  {monster_id: 30, item_id: 97, amount: 1, rare: true},
  {monster_id: 31, item_id: 90, amount: 1, rare: false},
  {monster_id: 31, item_id: 72, amount: 1, rare: true},
  {monster_id: 32, item_id: 83, amount: 1, rare: false},
  {monster_id: 32, item_id: 2, amount: 2, rare: true},
  {monster_id: 33, item_id: 47, amount: 1, rare: false},
  {monster_id: 33, item_id: 49, amount: 2, rare: true},
  {monster_id: 34, item_id: 61, amount: 2, rare: false},
  {monster_id: 34, item_id: 95, amount: 1, rare: true},
  {monster_id: 35, item_id: 75, amount: 1, rare: false},
  {monster_id: 36, item_id: 61, amount: 1, rare: false},
  {monster_id: 37, item_id: 32, amount: 2, rare: false},
  {monster_id: 37, item_id: 11, amount: 1, rare: true},
  {monster_id: 38, item_id: 73, amount: 1, rare: false},
  {monster_id: 38, item_id: 89, amount: 1, rare: true},
  {monster_id: 39, item_id: 52, amount: 1, rare: false},
  {monster_id: 39, item_id: 52, amount: 2, rare: true},
  {monster_id: 40, item_id: 84, amount: 1, rare: false},
  {monster_id: 40, item_id: 84, amount: 2, rare: true},
  {monster_id: 41, item_id: 98, amount: 1, rare: false},
  {monster_id: 41, item_id: 98, amount: 2, rare: true},
  {monster_id: 42, item_id: 52, amount: 1, rare: false},
  {monster_id: 42, item_id: 52, amount: 2, rare: true},
  {monster_id: 43, item_id: 52, amount: 4, rare: false},
  {monster_id: 44, item_id: 52, amount: 2, rare: false},
  {monster_id: 45, item_id: 72, amount: 2, rare: false},
  {monster_id: 46, item_id: 75, amount: 1, rare: false},
  {monster_id: 46, item_id: 88, amount: 1, rare: true},
  {monster_id: 47, item_id: 90, amount: 1, rare: false},
  {monster_id: 47, item_id: 72, amount: 1, rare: true},
  {monster_id: 48, item_id: 15, amount: 2, rare: false},
  {monster_id: 48, item_id: 21, amount: 1, rare: true},
  {monster_id: 49, item_id: 75, amount: 1, rare: false},
  {monster_id: 49, item_id: 43, amount: 1, rare: true},
  {monster_id: 50, item_id: 38, amount: 1, rare: false},
  {monster_id: 50, item_id: 53, amount: 1, rare: true},
  {monster_id: 51, item_id: 43, amount: 1, rare: false},
  {monster_id: 51, item_id: 43, amount: 2, rare: true},
  {monster_id: 52, item_id: 31, amount: 4, rare: false},
  {monster_id: 52, item_id: 32, amount: 1, rare: true},
  {monster_id: 53, item_id: 70, amount: 1, rare: false},
  {monster_id: 53, item_id: 70, amount: 2, rare: true},
  {monster_id: 54, item_id: 108, amount: 1, rare: false},
  {monster_id: 54, item_id: 108, amount: 2, rare: true},
  {monster_id: 55, item_id: 108, amount: 2, rare: false},
  {monster_id: 55, item_id: 95, amount: 1, rare: true},
  {monster_id: 56, item_id: 85, amount: 1, rare: false},
  {monster_id: 56, item_id: 28, amount: 1, rare: true},
  {monster_id: 57, item_id: 75, amount: 1, rare: false},
  {monster_id: 58, item_id: 39, amount: 2, rare: false},
  {monster_id: 58, item_id: 95, amount: 2, rare: true},
  {monster_id: 59, item_id: 15, amount: 2, rare: false},
  {monster_id: 59, item_id: 78, amount: 1, rare: true},
  {monster_id: 60, item_id: 15, amount: 2, rare: false},
  {monster_id: 60, item_id: 78, amount: 1, rare: true},
  {monster_id: 61, item_id: 16, amount: 2, rare: false},
  {monster_id: 61, item_id: 17, amount: 1, rare: true},
  {monster_id: 62, item_id: 33, amount: 1, rare: false},
  {monster_id: 62, item_id: 33, amount: 2, rare: true},
  {monster_id: 63, item_id: 70, amount: 4, rare: false},
  {monster_id: 63, item_id: 70, amount: 5, rare: true},
  {monster_id: 64, item_id: 25, amount: 1, rare: false},
  {monster_id: 64, item_id: 70, amount: 1, rare: true},
  {monster_id: 65, item_id: 85, amount: 1, rare: false},
  {monster_id: 65, item_id: 28, amount: 1, rare: true},
  {monster_id: 66, item_id: 26, amount: 1, rare: false},
  {monster_id: 66, item_id: 26, amount: 2, rare: true},
  {monster_id: 67, item_id: 43, amount: 1, rare: false},
  {monster_id: 67, item_id: 88, amount: 1, rare: true},
  {monster_id: 70, item_id: 48, amount: 1, rare: false},
  {monster_id: 70, item_id: 48, amount: 2, rare: true},
  {monster_id: 71, item_id: 48, amount: 1, rare: false},
  {monster_id: 71, item_id: 48, amount: 2, rare: true},
  {monster_id: 74, item_id: 73, amount: 1, rare: false},
  {monster_id: 74, item_id: 31, amount: 1, rare: true},
  {monster_id: 75, item_id: 26, amount: 1, rare: false},
  {monster_id: 75, item_id: 26, amount: 2, rare: true},
  {monster_id: 76, item_id: 8, amount: 4, rare: false},
  {monster_id: 76, item_id: 79, amount: 3, rare: true},
  {monster_id: 77, item_id: 79, amount: 1, rare: false},
  {monster_id: 77, item_id: 63, amount: 1, rare: true},
  {monster_id: 78, item_id: 38, amount: 1, rare: false},
  {monster_id: 78, item_id: 81, amount: 1, rare: true},
  {monster_id: 79, item_id: 33, amount: 2, rare: false},
  {monster_id: 79, item_id: 33, amount: 3, rare: true},
  {monster_id: 80, item_id: 43, amount: 1, rare: false},
  {monster_id: 80, item_id: 67, amount: 1, rare: true},
  {monster_id: 82, item_id: 43, amount: 1, rare: false},
  {monster_id: 82, item_id: 112, amount: 1, rare: true},
  {monster_id: 83, item_id: 43, amount: 1, rare: false},
  {monster_id: 83, item_id: 28, amount: 1, rare: true},
  {monster_id: 84, item_id: 43, amount: 1, rare: false},
  {monster_id: 84, item_id: 112, amount: 2, rare: true},
  {monster_id: 85, item_id: 46, amount: 3, rare: false},
  {monster_id: 85, item_id: 82, amount: 2, rare: true},
  {monster_id: 86, item_id: 75, amount: 1, rare: false},
  {monster_id: 87, item_id: 74, amount: 4, rare: false},
  {monster_id: 87, item_id: 78, amount: 2, rare: true},
  {monster_id: 88, item_id: 9, amount: 1, rare: false},
  {monster_id: 88, item_id: 9, amount: 2, rare: true},
  {monster_id: 89, item_id: 90, amount: 1, rare: false},
  {monster_id: 89, item_id: 72, amount: 1, rare: true},
  {monster_id: 90, item_id: 49, amount: 1, rare: false},
  {monster_id: 90, item_id: 49, amount: 2, rare: true},
  {monster_id: 91, item_id: 90, amount: 1, rare: false},
  {monster_id: 91, item_id: 72, amount: 1, rare: true},
  {monster_id: 92, item_id: 48, amount: 1, rare: false},
  {monster_id: 93, item_id: 48, amount: 4, rare: false},
  {monster_id: 93, item_id: 96, amount: 1, rare: true},
  {monster_id: 94, item_id: 72, amount: 4, rare: false},
  {monster_id: 94, item_id: 103, amount: 1, rare: true},
  {monster_id: 95, item_id: 52, amount: 4, rare: false},
  {monster_id: 95, item_id: 83, amount: 1, rare: true},
  {monster_id: 96, item_id: 52, amount: 4, rare: false},
  {monster_id: 96, item_id: 62, amount: 1, rare: true},
  {monster_id: 97, item_id: 8, amount: 1, rare: false},
  {monster_id: 97, item_id: 74, amount: 1, rare: true},
  {monster_id: 99, item_id: 40, amount: 1, rare: false},
  {monster_id: 99, item_id: 40, amount: 2, rare: true},
  {monster_id: 100, item_id: 95, amount: 4, rare: false},
  {monster_id: 100, item_id: 91, amount: 2, rare: true},
  {monster_id: 101, item_id: 43, amount: 1, rare: false},
  {monster_id: 101, item_id: 86, amount: 1, rare: true},
  {monster_id: 102, item_id: 43, amount: 1, rare: false},
  {monster_id: 102, item_id: 86, amount: 1, rare: true},
  {monster_id: 103, item_id: 95, amount: 1, rare: false},
  {monster_id: 104, item_id: 52, amount: 1, rare: false},
  {monster_id: 104, item_id: 52, amount: 2, rare: true},
  {monster_id: 105, item_id: 67, amount: 1, rare: false},
  {monster_id: 105, item_id: 100, amount: 1, rare: true},
  {monster_id: 106, item_id: 75, amount: 1, rare: false},
  {monster_id: 107, item_id: 43, amount: 2, rare: false},
  {monster_id: 107, item_id: 97, amount: 1, rare: true},
  {monster_id: 108, item_id: 108, amount: 2, rare: false},
  {monster_id: 108, item_id: 108, amount: 3, rare: true},
  {monster_id: 109, item_id: 43, amount: 1, rare: false},
  {monster_id: 109, item_id: 46, amount: 1, rare: true},
  {monster_id: 111, item_id: 79, amount: 1, rare: false},
  {monster_id: 112, item_id: 79, amount: 4, rare: false},
  {monster_id: 112, item_id: 61, amount: 2, rare: true},
  {monster_id: 113, item_id: 79, amount: 2, rare: false},
  {monster_id: 114, item_id: 31, amount: 2, rare: false},
  {monster_id: 114, item_id: 31, amount: 4, rare: true},
  {monster_id: 115, item_id: 61, amount: 1, rare: false},
  {monster_id: 115, item_id: 102, amount: 1, rare: true},
  {monster_id: 116, item_id: 34, amount: 2, rare: false},
  {monster_id: 116, item_id: 23, amount: 2, rare: true},
  {monster_id: 117, item_id: 5, amount: 2, rare: false},
  {monster_id: 118, item_id: 40, amount: 2, rare: false},
  {monster_id: 118, item_id: 40, amount: 3, rare: true},
  {monster_id: 119, item_id: 5, amount: 1, rare: false},
  {monster_id: 119, item_id: 5, amount: 2, rare: true},
  {monster_id: 120, item_id: 5, amount: 1, rare: false},
  {monster_id: 120, item_id: 5, amount: 2, rare: true},
  {monster_id: 121, item_id: 40, amount: 1, rare: false},
  {monster_id: 121, item_id: 36, amount: 2, rare: true},
  {monster_id: 122, item_id: 40, amount: 3, rare: false},
  {monster_id: 122, item_id: 40, amount: 4, rare: true},
  {monster_id: 123, item_id: 90, amount: 1, rare: false},
  {monster_id: 123, item_id: 72, amount: 1, rare: true},
  {monster_id: 124, item_id: 75, amount: 1, rare: false},
  {monster_id: 124, item_id: 88, amount: 1, rare: true},
  {monster_id: 131, item_id: 43, amount: 1, rare: false},
  {monster_id: 131, item_id: 46, amount: 1, rare: true},
  {monster_id: 132, item_id: 43, amount: 1, rare: false},
  {monster_id: 132, item_id: 39, amount: 1, rare: true},
  {monster_id: 133, item_id: 74, amount: 1, rare: false},
  {monster_id: 133, item_id: 74, amount: 2, rare: true},
  {monster_id: 134, item_id: 98, amount: 4, rare: false},
  {monster_id: 134, item_id: 105, amount: 1, rare: true},
  {monster_id: 135, item_id: 43, amount: 1, rare: false},
  {monster_id: 136, item_id: 56, amount: 1, rare: false},
  {monster_id: 136, item_id: 107, amount: 1, rare: true},
  {monster_id: 137, item_id: 38, amount: 1, rare: false},
  {monster_id: 137, item_id: 37, amount: 1, rare: true},
  {monster_id: 138, item_id: 43, amount: 1, rare: false},
  {monster_id: 138, item_id: 39, amount: 1, rare: true},
  {monster_id: 140, item_id: 79, amount: 1, rare: false},
  {monster_id: 140, item_id: 79, amount: 2, rare: true},
  {monster_id: 141, item_id: 23, amount: 2, rare: false},
  {monster_id: 141, item_id: 108, amount: 2, rare: true},
  {monster_id: 142, item_id: 95, amount: 1, rare: false},
  {monster_id: 142, item_id: 95, amount: 2, rare: true},
  {monster_id: 143, item_id: 38, amount: 50, rare: false},
  {monster_id: 144, item_id: 52, amount: 3, rare: false},
  {monster_id: 144, item_id: 11, amount: 1, rare: true},
  {monster_id: 145, item_id: 80, amount: 1, rare: false},
  {monster_id: 145, item_id: 17, amount: 1, rare: true},
  {monster_id: 146, item_id: 23, amount: 2, rare: false},
  {monster_id: 146, item_id: 108, amount: 1, rare: true},
  {monster_id: 147, item_id: 40, amount: 1, rare: false},
  {monster_id: 147, item_id: 40, amount: 2, rare: true},
  {monster_id: 149, item_id: 89, amount: 4, rare: false},
  {monster_id: 149, item_id: 15, amount: 1, rare: true},
  {monster_id: 150, item_id: 33, amount: 3, rare: false},
  {monster_id: 150, item_id: 33, amount: 4, rare: true},
  {monster_id: 151, item_id: 16, amount: 1, rare: false},
  {monster_id: 152, item_id: 8, amount: 1, rare: false},
  {monster_id: 152, item_id: 79, amount: 1, rare: true},
  {monster_id: 153, item_id: 75, amount: 1, rare: false},
  {monster_id: 153, item_id: 46, amount: 1, rare: true},
  {monster_id: 154, item_id: 90, amount: 1, rare: false},
  {monster_id: 154, item_id: 72, amount: 1, rare: true},
  {monster_id: 155, item_id: 14, amount: 1, rare: false},
  {monster_id: 155, item_id: 14, amount: 2, rare: true},
  {monster_id: 156, item_id: 23, amount: 1, rare: false},
  {monster_id: 156, item_id: 23, amount: 2, rare: true},
  {monster_id: 157, item_id: 112, amount: 1, rare: false},
  {monster_id: 157, item_id: 83, amount: 1, rare: true},
  {monster_id: 159, item_id: 34, amount: 2, rare: false},
  {monster_id: 159, item_id: 23, amount: 2, rare: true},
  {monster_id: 160, item_id: 34, amount: 2, rare: false},
  {monster_id: 160, item_id: 23, amount: 1, rare: true},
  {monster_id: 162, item_id: 104, amount: 1, rare: false},
  {monster_id: 162, item_id: 104, amount: 2, rare: true},
  {monster_id: 163, item_id: 88, amount: 2, rare: false},
  {monster_id: 164, item_id: 79, amount: 2, rare: false},
  {monster_id: 164, item_id: 70, amount: 10, rare: true},
  {monster_id: 165, item_id: 82, amount: 2, rare: false},
  {monster_id: 165, item_id: 95, amount: 2, rare: true},
  {monster_id: 166, item_id: 104, amount: 1, rare: false},
  {monster_id: 168, item_id: 102, amount: 2, rare: false},
  {monster_id: 168, item_id: 102, amount: 3, rare: true},
  {monster_id: 169, item_id: 83, amount: 1, rare: false},
  {monster_id: 169, item_id: 100, amount: 1, rare: true},
  {monster_id: 170, item_id: 38, amount: 1, rare: false},
  {monster_id: 170, item_id: 103, amount: 1, rare: true},
  {monster_id: 171, item_id: 46, amount: 1, rare: false},
  {monster_id: 171, item_id: 46, amount: 2, rare: true},
  {monster_id: 172, item_id: 89, amount: 1, rare: false},
  {monster_id: 172, item_id: 89, amount: 2, rare: true},
  {monster_id: 173, item_id: 28, amount: 1, rare: false},
  {monster_id: 173, item_id: 100, amount: 1, rare: true},
  {monster_id: 174, item_id: 95, amount: 3, rare: false},
  {monster_id: 174, item_id: 95, amount: 4, rare: true},
  {monster_id: 181, item_id: 98, amount: 1, rare: false},
  {monster_id: 181, item_id: 83, amount: 1, rare: true},
  {monster_id: 183, item_id: 75, amount: 1, rare: false},
  {monster_id: 184, item_id: 75, amount: 1, rare: false},
  {monster_id: 185, item_id: 24, amount: 1, rare: false},
  {monster_id: 185, item_id: 24, amount: 2, rare: true},
  {monster_id: 186, item_id: 74, amount: 4, rare: false},
  {monster_id: 186, item_id: 32, amount: 1, rare: true},
  {monster_id: 187, item_id: 7, amount: 2, rare: false},
  {monster_id: 188, item_id: 88, amount: 1, rare: false},
  {monster_id: 188, item_id: 88, amount: 2, rare: true},
  {monster_id: 190, item_id: 28, amount: 1, rare: false},
  {monster_id: 190, item_id: 104, amount: 1, rare: true},
  {monster_id: 191, item_id: 28, amount: 1, rare: false},
  {monster_id: 191, item_id: 104, amount: 1, rare: true},
  {monster_id: 192, item_id: 41, amount: 1, rare: false},
  {monster_id: 192, item_id: 41, amount: 2, rare: true},
  {monster_id: 193, item_id: 40, amount: 1, rare: false},
  {monster_id: 193, item_id: 36, amount: 1, rare: true},
  {monster_id: 194, item_id: 89, amount: 3, rare: false},
  {monster_id: 194, item_id: 95, amount: 2, rare: true},
  {monster_id: 196, item_id: 48, amount: 4, rare: false},
  {monster_id: 196, item_id: 52, amount: 4, rare: true},
  {monster_id: 197, item_id: 38, amount: 1, rare: false},
  {monster_id: 197, item_id: 101, amount: 1, rare: true},
  {monster_id: 198, item_id: 85, amount: 2, rare: false},
  {monster_id: 198, item_id: 28, amount: 1, rare: true},
  {monster_id: 199, item_id: 26, amount: 1, rare: false},
  {monster_id: 199, item_id: 26, amount: 2, rare: true},
  {monster_id: 200, item_id: 43, amount: 1, rare: false},
  {monster_id: 200, item_id: 31, amount: 1, rare: true},
  {monster_id: 201, item_id: 40, amount: 1, rare: false},
  {monster_id: 201, item_id: 40, amount: 3, rare: true},
  {monster_id: 202, item_id: 38, amount: 1, rare: false},
  {monster_id: 202, item_id: 55, amount: 1, rare: true},
  {monster_id: 203, item_id: 22, amount: 10, rare: false},
  {monster_id: 203, item_id: 22, amount: 20, rare: true},
  {monster_id: 204, item_id: 43, amount: 1, rare: false},
  {monster_id: 204, item_id: 43, amount: 2, rare: true},
  {monster_id: 205, item_id: 32, amount: 1, rare: false},
  {monster_id: 205, item_id: 83, amount: 1, rare: true},
  {monster_id: 206, item_id: 49, amount: 4, rare: false},
  {monster_id: 206, item_id: 63, amount: 1, rare: true},
  {monster_id: 207, item_id: 41, amount: 2, rare: false},
  {monster_id: 207, item_id: 96, amount: 1, rare: true},
  {monster_id: 209, item_id: 43, amount: 2, rare: false},
  {monster_id: 209, item_id: 78, amount: 1, rare: true},
  {monster_id: 210, item_id: 43, amount: 1, rare: false},
  {monster_id: 210, item_id: 78, amount: 1, rare: true},
  {monster_id: 211, item_id: 43, amount: 1, rare: false},
  {monster_id: 211, item_id: 74, amount: 1, rare: true},
  {monster_id: 212, item_id: 34, amount: 1, rare: false},
  {monster_id: 212, item_id: 23, amount: 1, rare: true},
  {monster_id: 213, item_id: 43, amount: 1, rare: false},
  {monster_id: 213, item_id: 112, amount: 1, rare: true},
  {monster_id: 214, item_id: 7, amount: 1, rare: false},
  {monster_id: 214, item_id: 7, amount: 2, rare: true},
  {monster_id: 216, item_id: 31, amount: 1, rare: false},
  {monster_id: 216, item_id: 32, amount: 1, rare: true},
  {monster_id: 217, item_id: 43, amount: 1, rare: false},
  {monster_id: 217, item_id: 67, amount: 1, rare: true},
  {monster_id: 218, item_id: 44, amount: 3, rare: false},
  {monster_id: 218, item_id: 28, amount: 2, rare: true},
  {monster_id: 219, item_id: 79, amount: 1, rare: false},
  {monster_id: 219, item_id: 28, amount: 1, rare: true},
  {monster_id: 220, item_id: 26, amount: 1, rare: false},
  {monster_id: 220, item_id: 50, amount: 1, rare: true},
  {monster_id: 221, item_id: 55, amount: 1, rare: false},
  {monster_id: 221, item_id: 55, amount: 2, rare: true},
  {monster_id: 222, item_id: 44, amount: 3, rare: false},
  {monster_id: 222, item_id: 28, amount: 2, rare: true},
  {monster_id: 223, item_id: 79, amount: 1, rare: false},
  {monster_id: 223, item_id: 28, amount: 1, rare: true},
  {monster_id: 225, item_id: 90, amount: 1, rare: false},
  {monster_id: 225, item_id: 72, amount: 1, rare: true},
  {monster_id: 229, item_id: 67, amount: 1, rare: false},
  {monster_id: 229, item_id: 32, amount: 1, rare: true},
  {monster_id: 230, item_id: 72, amount: 1, rare: false},
  {monster_id: 230, item_id: 72, amount: 3, rare: true},
  {monster_id: 231, item_id: 89, amount: 3, rare: false},
  {monster_id: 231, item_id: 89, amount: 4, rare: true}
]) if StealDrop.count == 0
